"""Initial migration with user and test models

Revision ID: 22a5aede0563
Revises: 
Create Date: 2025-03-27 12:54:12.506836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a5aede0563'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('encrypted_api_key', sa.String(length=512), nullable=True),
    sa.Column('api_key_set', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('test_definition',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source_text_snippet', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempt',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_definition_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_started', sa.DateTime(), nullable=False),
    sa.Column('timestamp_completed', sa.DateTime(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_definition_id'], ['test_definition.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_definition_id', sa.String(length=36), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=True),
    sa.Column('correct_answer_info_json', sa.Text(), nullable=True),
    sa.Column('suggested_answer', sa.Text(), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['test_definition_id'], ['test_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('user_input', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='_attempt_question_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_table('question')
    op.drop_table('attempt')
    op.drop_table('test_definition')
    op.drop_table('user')
    # ### end Alembic commands ###
